name: CI

on:
  push:
    branches: [ main, develop, staging ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
      
    - name: Cache Swift Package Manager dependencies
      uses: actions/cache@v3
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
          
    - name: Create Secrets.swift for CI
      run: |
        # Create Config directory if it doesn't exist
        mkdir -p Joanie/Config
        
        # Create Secrets.swift for CI build with placeholder values
        cat > Joanie/Config/Secrets.swift << 'EOF'
        import Foundation

        struct Secrets {
            // MARK: - Supabase Configuration
            // SECURITY: Use environment variables in production
            static let supabaseURL = ProcessInfo.processInfo.environment["SUPABASE_URL"] ?? "https://your-project-id.supabase.co"
            static let supabaseAnonKey = ProcessInfo.processInfo.environment["SUPABASE_ANON_KEY"] ?? "your-anon-key-here"
            static let supabaseServiceRoleKey = ProcessInfo.processInfo.environment["SUPABASE_SERVICE_ROLE_KEY"] ?? "your-service-role-key-here"
            
            // MARK: - AI API Keys
            // SECURITY: Use environment variables in production
            static let openAIAPIKey = ProcessInfo.processInfo.environment["OPENAI_API_KEY"] ?? "your-openai-api-key-here"
            static let xAIAPIKey = ProcessInfo.processInfo.environment["XAI_API_KEY"] ?? "your-xai-api-key-here"
            
            // MARK: - App Configuration
            // SECURITY: Use environment variables in production
            static let appEnvironment = ProcessInfo.processInfo.environment["APP_ENVIRONMENT"] ?? "development"
            static let debugMode = ProcessInfo.processInfo.environment["DEBUG_MODE"] == "true"
        }
        EOF
        
    - name: Build project
      run: |
        # Set up build environment
        export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
        export DERIVED_DATA_PATH=/tmp/DerivedData
        
        # Create derived data directory with proper permissions
        mkdir -p $DERIVED_DATA_PATH
        chmod 755 $DERIVED_DATA_PATH
        
        xcodebuild -project Joanie.xcodeproj \
          -scheme Joanie \
          -destination 'generic/platform=iOS Simulator' \
          -configuration Debug \
          -derivedDataPath $DERIVED_DATA_PATH \
          clean build
          
  lint:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install SwiftLint
      run: |
        brew install swiftlint
        
    - name: Run SwiftLint
      run: |
        swiftlint lint --reporter github-actions-logging
        
  security-scan:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run security scan
      run: |
        # Check for hardcoded secrets (excluding config files that contain patterns for detection)
        if grep -r "sk-" . --exclude-dir=.git --exclude-dir=DerivedData --exclude=".swiftlint.yml" --exclude=".github" --exclude="*.yml"; then
          echo "Potential API key found in code"
          exit 1
        fi
        
        # Check for TODO/FIXME comments that might indicate security issues
        if grep -r "TODO.*security\|FIXME.*security" . --exclude-dir=.git --exclude-dir=DerivedData --exclude=".github" --exclude="*.yml"; then
          echo "Security-related TODO/FIXME found"
          exit 1
        fi
        
        echo "Security scan passed - no hardcoded secrets or security TODOs found"
